config/routes.rb
SipMonitor::Application.routes.draw do

  resources :subscribers do
    collection do
      get 'search'
      get 'online_test'
    end
    get 'online_test', :on => :member
  end
  resources :alarms do
    collection do
      get 'statistics'
    end
  end

  get "login" => "sessions#new", :as => "login"

  root :to => "sessions#new"

  resources :users
  resources :sessions

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SipMonitor</title>
    <!--<%= stylesheet_link_tag    "application", :media => "all" %> -->



    <%= stylesheet_link_tag "dashboard/1col.css", :rel=>"alternate stylesheet", :media => "screen,projection", :title=>"1col" %>
    <%= stylesheet_link_tag "dashboard/2col.css", :media => "screen,projection", :title=>"2col" %>
    <%= stylesheet_link_tag "dashboard/main", "dashboard/reset", "dashboard/style", "dashboard/mystyle", :media => "screen,projection" %>
    <%= stylesheet_link_tag "sessions", :media => "all" %>
    <!--[if lte IE 6]>
    <%=stylesheet_link_tag "dashboard/main-ie6", :media => "screen,projection" %>
    <![endif]-->

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>


    <script type="text/javascript">
      $(document).ready(function(){
          $(".tabs > ul").tabs();
          });
        </script>




       <%= javascript_tag do %>
          $(document).ready(
          function(){
          setInterval(function(){
          $.ajax({
          url: "<%= "/alarms" %>",
          type: "GET",
          dataType: "script"
          });
          }, 10000 );
          });
        <% end %>






        <title>Adminizio Lite</title>

      </head>









      <body>

        <div id="main">

          <!-- Tray -->
          <div id="tray" class="box">

            <p class="f-left box">

              <!-- Switcher -->
              <span class="f-left" id="switcher">
                <a href="#" rel="1col" class="styleswitch ico-col1" title="Скрыть колонку поиска">


                  <%= image_tag("design/switcher-1col.gif", :alt=>"2 Columns") %>

                </a>
                <a href="#" rel="2col" class="styleswitch ico-col2" title="Отобразить колонку поиска">



                  <%= image_tag("design/switcher-2col.gif", :alt=>"2 Columns") %>



                </a>
              </span>

              Проект: <strong>Отслеживание состояния регистрации SIP абонентов</strong>
            </p>
                        <p class="f-right"> Пользователь: <strong><a href="#"><%= current_user.email %></a></strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><%= link_to("Выход", "/sessions/#{current_user.id}", :method => :delete, :confirm => "Вы уверены, что хотите выйти?") %></strong></p>



          </div> <!--  /tray -->

          <hr class="noscreen" />

          <!-- Menu -->
          <div id="menu" class="box">
            <!-- Я закоментировал
            <ul class="box f-right">
              <li><a href="#"><span><strong>Visit Site &raquo;</strong></span></a></li>
            </ul>
            -->

            <ul class="box">		
              <li id="menu-active"><%= link_to(:controller => "alarms") do %><span>Аварийная панель</span><% end %></li> <!-- Active -->


              <li><%= link_to(:controller => "subscribers", :action => "index") do %><span>База данных абонентов</span><% end %></li>


              <li><a href="/alarms/statistics"><span>Статистика</span></a></li>
              
              <!-- <li><%= link_to users_path do %><span>Пользователи</span><% end %></li>-->



              	
<!-- Управление аудио проигрывателем              
              <li class="f-right"><%= audio_tag "Critical.wav", :controls => true, :autobuffer => true, :autoplay => false, :loop => true %></li>
-->
            </ul>

          </div> <!-- /header -->

          <hr class="noscreen" />

          <!-- Columns -->
          <div id="cols" class="box">

            <!-- Aside (Left Column) -->
            <div id="aside" class="box">

              <div class="padding box">


                <!-- Logo (Max. width = 200px) -->
                <!-- <p><%= image_tag("SIP_NGN.png", :width=>'200px', :alt=>"SIP_NGN.png", :title=>"") %> </p> -->

                <!-- Search -->

                <%= form_tag(search_subscribers_path, :method => "get", :id=>"search") do %>
                  <fieldset>
                    <legend>Номер абонента</legend>
                    <p><%= telephone_field_tag(:number, nil, :class => 'input-text', :size => 17, :placeholder=>"10 знаков", :maxlength => 10, pattern: "8[0-9]{9,}") %>&nbsp;<%= submit_tag("OK", :class => 'input-submit-02') %><br />
                    </fieldset>
                  <% end %> 



                 

















                  <!-- Create a new project -->
                  <p id="btn-create" class="box"><%= link_to(:controller => "subscribers", :action => "new") do %><span>Добавить абонента</span><% end %></p>

                </div> <!-- /padding -->



              </div> <!-- /aside -->

              <hr class="noscreen" />

              <!-- Content (Right Column) -->
              <div id="content" class="box">








                <%= yield %>












              </div> <!-- /content -->

            </div> <!-- /cols -->

            <hr class="noscreen" />

            <!-- Footer -->
            <div id="footer" class="box">
              <p class="f-left">&copy; 2012 <a href="mailto:s.sintyalev@nnov.volga.rt.ru?subject=Вопрос по программе 'Отслеживание состояния регистрации SIP абонентов'">Синтялёв Сергей Владимирович</a>&nbsp;&nbsp;<strong>Ver. 0.1</strong></p>



            </div> <!-- /footer -->

          </div> <!-- /main -->


        </body>














































</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Авторизация</title>
 
<%= stylesheet_link_tag "sessions", :media => "all" %>
<%= stylesheet_link_tag "dashboard/main", "dashboard/reset", "dashboard/style", "dashboard/mystyle", :media => "screen,projection" %>

</head>

  <%= yield %>


</html>

app/views/layouts/users.html.erb
  <%= yield %>